### ISSUE TITLE
Question: signature verification for Tezos

### ISSUE THREAD

**Issue by wout** [didactic-drunk/sodium.cr#17]
I'm trying to implement server-side signature verification for a Tezos wallet (Temple). This is basically what I'm trying to accomplish in Crystal:

https://replit.com/@DalyIng/verifyTezosSignature#index.js

My problem is I keep getting verification failures. I'm probably doing it wrong and I was wondering if you could point out the flaw in my approach.

Since there wasn't a Base58 shard that worked with the bitcoin alphabet and decoded to bytes, I've ported a shard from Ruby (https://github.com/wout/base58/).

That said, what I'm failing with is this:

```crystal
PREFIX = {
  edsig: Bytes[9, 245, 205, 134, 18],
  edpk:  Bytes[13, 15, 37, 217],
}

message = "Hello World!" # => 05013438343836353663366336663230353736663732366336343231 in the wallet preview
digest = Sodium::Digest::Blake2b.new(32)
digest.update(message.to_slice)

pk = "edpkv64LreZSdPfjUVuWTa32MbKVGwrKV9V9X9fSNDzghMkj6TV9uN"
sig = "edsigtyZK2y7eAw3oWq8X7h42f2tQWwp9D5Kw7kAT4WuUjMXBiaoB1kChQNCo4kRvGefxBTnyz2AmWP319GLzxLacneJqFdk4t3"

pkb = Base58::Bytes.decode(pk, Base58::BITCOIN)[PREFIX[:edpk].size..][..31]
sigb = Base58::Bytes.decode(sig, Base58::BITCOIN)[PREFIX[:edsig].size..][..63]
public_key = Sodium::Sign::PublicKey.new(pkb)

public_key.verify_detached(digest.hexfinal, sigb)
```

Clearly, I'm doing something wrong. Can you point me in the right direction?

**Comment by didactic-drunk** [comment]
The sodium shard is used correctly.  I guess it's the decoding or data.  Verify `pkb`, `signb`, `digest.hexfinal` against another source?

**Comment by wout** [comment]
Using the data from the JS example, it does work. As it turns out, there was nothing wrong with the backend code but I was signing the message incorrectly. I used the [RAW method](https://docs.walletbeacon.io/guides/sign-payload#raw) instead of the [HEX with 03 prefix](https://docs.walletbeacon.io/guides/sign-payload#hex-prefixed-with-03) method. Now it does work as expected.

Thanks for having a look at it!
