### ISSUE TITLE
How to change a sign ed25519 public/singing keys to curve25519

### ISSUE THREAD

**Issue by Hamdy** [didactic-drunk/sodium.cr#8]
Hi, I have a case where I need to convert keys into curve25519
is there a simple way to do it? I could not see that supported in the library API

thanks

**Comment by didactic-drunk** [comment]
Check out the most recent commit in master.   I'm not in a position to test it.  Feel free to submit specs from other bindings.

**Comment by Hamdy** [comment]
Hi, thanks for adding it, I appreciate if you can add also, same for public signing key 
we have a use case that uses this as well, and I can do some testing and provide feedback 
thanks

**Comment by Hamdy** [comment]
Hi
I've this piece of working python code
```
nonce = base64.b64decode(data['data']['nonce'])
ciphertext = base64.b64decode(data['data']['ciphertext'])
private_key = nacl.signing.SigningKey(app.config['private_key'], encoder=nacl.encoding.Base64Encoder)

  box = Box(
    private_key.to_curve25519_private_key(),
    user_pub_key.to_curve25519_public_key()
  )

  try:
    decrypted = box.decrypt(ciphertext, nonce)
    result = json.loads(decrypted)
  except:
    return abort(400, jsonify({'message': 'Error decrypting'}))
```

i'm trying to make similar behavior in crystal but I still have issues in decryption 
I use the following code, but I always get decryption failure
any ideas of what might be missing here ?

```
 nonce = Base64.decode(verified_data.data.nonce)
    ciphertext = Base64.decode(verified_data.data.ciphertext)

    sekret_curve = SEKRET.to_curve25519
    public_curve = user_public_key.not_nil!.to_curve25519

    sekret_curve.box public_curve do |box|
      decrypted = box.decrypt src: ciphertext, nonce: Sodium::Nonce.new nonce
    end
```

the full python app that is working is here https://github.com/threefoldtech/threefold-forums/blob/staging/3bot/app.py
the crystal snippet  is here : https://gist.github.com/Hamdy/a82894cc1b67522ea0c323361e5c0bd9  
the problem is starting at line 133

**Comment by didactic-drunk** [comment]
May I suggest printing a Base64 key/output for each step and comparing  between implementations?

p Base64.encode(SEKRET.to_slice)
p ...pubkey...
p box.encrypt ...

I'm currently injured and not in a position to debug thoroughly.

**Comment by Hamdy** [comment]
Oh, am really sorry for this! 
OK, I'll do some comparison

**Comment by Hamdy** [comment]
I got it to work, my bad .. I was using a new secret key each time I start my app which was wrong
also I didn't know a proper way to load same secret key each time
I didn't find a way to get `seed ` from secret key so I can export it and reuse it , 
I ended up using some seed used in unit tests 

```
# SEED = "b18e1d0045995ec3d010c387ccfeb984d783af8fbb0f40fa7db126d889f6dadd".hexbytes
# pp! "SEED: #{Base64.encode(SEED)}"

SEED = Base64.decode("sY4dAEWZXsPQEMOHzP65hNeDr4+7D0D6fbEm2In22t0=\n")
SEKRET = Sodium::Sign::SecretKey.new seed: SEED

PUBLICKEY = SEKRET.public_key.to_curve25519

```

I could not do something like `secret.seed` as seed is not exposed and I guess it's nil in some cases
I think it needs to be populated with the proper seed, so it can be exported

Thank you

**Comment by didactic-drunk** [comment]
Try now.

**Comment by Hamdy** [comment]
works fine, thank you !
