### ISSUE TITLE
Failed postinstall of sodium on ./build/libsodium_install.sh:

### ISSUE THREAD

**Issue by volker-schukai** [didactic-drunk/sodium.cr#9]
System: Debian 10 (buster)

> A recent version of libsodium is automatically downloaded and compiled if you don't install your own version.

installed:
``` 
libsodium23/stable,now 1.0.17-1 amd64  [installiert]
``` 

``` 
Failed postinstall of sodium on ./build/libsodium_install.sh:
--2020-07-15 10:27:49--  https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz.minisig
Auflösen des Hostnamens download.libsodium.org (download.libsodium.org)… 37.59.238.213
Verbindungsaufbau zu download.libsodium.org (download.libsodium.org)|37.59.238.213|:443 … verbunden.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [70]: Error in protocol version
Es ist nicht möglich, eine SSL-Verbindung herzustellen.
``` 

installed:
``` 
libsodium-dev/stable,now 1.0.17-1 amd64  [installiert]
libsodium23/stable,now 1.0.17-1 amd64  [installiert]
``` 

error-message:

``` 
Resolving dependencies
Fetching https://github.com/didactic-drunk/sodium.cr.git
Installing sodium (1.2.0)
Postinstall of sodium: ./build/libsodium_install.sh
Failed postinstall of sodium on ./build/libsodium_install.sh:
./build/env.sh: Zeile 22: [: Fehlende `]'
```

**Comment by volker-schukai** [comment]
after installing version 1.0.18 it worked

libsodium-dev/unbekannt,now 1.0.18-1+0~20191009.1+debian10~1.gbpb6823f amd64  [installiert]
libsodium23/unbekannt,now 1.0.18-1+0~20191009.1+debian10~1.gbpb6823f amd64  [installiert]

**Comment by didactic-drunk** [comment]
Looks like a TLS error:
> Verbindungsaufbau zu download.libsodium.org (download.libsodium.org)|37.59.238.213|:443 … verbunden.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [70]: Error in protocol version

Why does `wget` fail?   I don't have a deb10 system, but ubuntu seems to download fine.  Was that a temporary error? What happens if you run `wget ` yourself?

**Comment by didactic-drunk** [comment]
Feel free to close the issue if it's working for you and you don't want to debug further.
